apiVersion: apps/v1
kind: Deployment
metadata:
  name: realio-network-frontend
  namespace: realio-network-frontend
spec:
  selector:
    matchLabels:
      app: realio-network-frontend
  template:
    metadata:
      labels:
        app: realio-network-frontend
    spec:
      containers:
      - name: realio-network-frontend
        image: registry.digitalocean.com/kubernetes-prod/realio-network-frontend:latest
  replicas: 2