---
kind: Service
apiVersion: v1
metadata:
  name: ingress-aliases
  namespace: realio-network-frontend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: realiostage.network,www.realiostage.network
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: ingress.realiostage.network
